services:
  _instanceof:
    HeimrichHannot\ReaderBundle\ConfigElementType\ReaderConfigElementTypeInterface:
      tags: ['huh.reader.config_element_type']
      public: false
      autowire: true

  HeimrichHannot\ReaderBundle\ConfigElementType\ListConfigElementType: ~