huh:
    reader:
        managers:
            - { name: default, id: huh.reader.manager.reader }
        items:
            - { name: default, class: HeimrichHannot\ReaderBundle\Item\DefaultItem }
        config_element_types:
            - { name: list, class: HeimrichHannot\ReaderBundle\ConfigElementType\ListConfigElementType }
            - { name: navigation, class: HeimrichHannot\ReaderBundle\ConfigElementType\NavigationConfigElementType }
            - { name: syndication, class: HeimrichHannot\ReaderBundle\ConfigElementType\SyndicationConfigElementType }
            - { name: redirection, class: HeimrichHannot\ReaderBundle\ConfigElementType\RedirectionConfigElementType }
            - { name: delete, class: HeimrichHannot\ReaderBundle\ConfigElementType\DeleteConfigElementType }
        templates:
            item:
                - { name: default, template: "@HeimrichHannotContaoReader/reader_item_default.html.twig" }
            item_prefixes:
                - reader_item_
                - item_
                - news_
                - event_
        syndications:
            - { name: facebook, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\FacebookSyndication, sort: 0 }
            - { name: twitter, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\TwitterSyndication, sort: 1 }
            - { name: linkedin, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\LinkedInSyndication, sort: 6 }
            - { name: xing, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\XingSyndication, sort: 5 }
            - { name: pdf, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PdfSyndication, sort: 3 }
            - { name: mail, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\MailSyndication, sort: 2 }
            - { name: print, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PrintSyndication, sort: 4 }
            - { name: ics, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\IcsSyndication, sort: 12 }
            - { name: tumblr, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\TumblrSyndication, sort: 7}
            - { name: pinterest, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PinterestSyndication, sort: 8 }
            - { name: reddit, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\RedditSyndication, sort: 10 }
            - { name: whatsapp, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\WhatsAppSyndication, sort: 9 }
        syndication_pdf_readers:
            - { name: default, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PdfReader\DefaultPdfReader }
        delete_classes:
            - { name: default, class: HeimrichHannot\ReaderBundle\ConfigElementType\Delete\DefaultDelete }