huh:
    reader:
        managers:
            - { name: default, id: huh.reader.manager.reader }
        items:
            - { name: default, class: HeimrichHannot\ReaderBundle\Item\DefaultItem }
        config_element_types:
            - { name: image, class: HeimrichHannot\ReaderBundle\ConfigElementType\ImageConfigElementType }
            - { name: list, class: HeimrichHannot\ReaderBundle\ConfigElementType\ListConfigElementType }
            - { name: navigation, class: HeimrichHannot\ReaderBundle\ConfigElementType\NavigationConfigElementType }
            - { name: syndication, class: HeimrichHannot\ReaderBundle\ConfigElementType\SyndicationConfigElementType }
        templates:
            item:
                - { name: default, template: "@HeimrichHannotContaoReader/reader_item_default.html.twig" }
            item_prefixes:
                - reader_item_
                - item_
                - news_
                - event_
        syndications:
            - { name: facebook, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\FacebookSyndication }
            - { name: twitter, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\TwitterSyndication }
            - { name: googleplus, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\GooglePlusSyndication }
            - { name: linkedin, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\LinkedInSyndication }
            - { name: xing, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\XingSyndication }
            - { name: pdf, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PdfSyndication }
            - { name: mail, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\MailSyndication }
            - { name: print, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PrintSyndication }
            - { name: tumblr, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\TumblrSyndication }
            - { name: pinterest, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PinterestSyndication }
            - { name: reddit, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\RedditSyndication }
            - { name: whatsapp, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\WhatsAppSyndication }
        syndication_pdf_readers:
            - { name: default, class: HeimrichHannot\ReaderBundle\ConfigElementType\Syndication\PdfReader\DefaultPdfReader }