huh:
    reader:
        config_element_types:
            - {name: image, class: HeimrichHannot\ReaderBundle\ConfigElementType\ImageConfigElementType}
            - {name: list, class: HeimrichHannot\ReaderBundle\ConfigElementType\ListConfigElementType}
        templates:
            item:
                - { name: default, template: "@HeimrichHannotContaoReader/reader_item_default.html.twig" }