services:
  huh.reader.listener.callback.readerconfigelement:
    class: HeimrichHannot\ReaderBundle\EventListener\ReaderConfigCallbackListener
    arguments: ['@contao.framework', '@translator', '@huh.utils.model']

  HeimrichHannot\ReaderBundle\EventListener\AdjustFilterValueEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_value_event, method: onAdjustFilterValue }