services:
  _defaults:
    public: true

  _instanceof:
    HeimrichHannot\ReaderBundle\ConfigElementType\ReaderConfigElementTypeInterface:
      tags: ['huh.reader.config_element_type']
      public: false
      autowire: true

  huh.reader.backend.reader-config:
    class: HeimrichHannot\ReaderBundle\Backend\ReaderConfig
    arguments:
      - "@contao.framework"
      - "@huh.reader.reader-config-registry"
      - "@huh.utils.model"
      - "@huh.utils.dca"

  huh.reader.backend.reader-config-element:
    class: HeimrichHannot\ReaderBundle\Backend\ReaderConfigElement
    arguments:
      - "@contao.framework"

  huh.reader.choice.template.item:
    class: HeimrichHannot\ReaderBundle\Choice\ReaderItemTemplateChoice
    arguments:
      - "@contao.framework"

  huh.reader.choice.manager:
    class: HeimrichHannot\ReaderBundle\Choice\ManagerChoice
    arguments:
      - "@contao.framework"

  huh.reader.choice.item:
    class: HeimrichHannot\ReaderBundle\Choice\ItemChoice
    arguments:
      - "@contao.framework"

  huh.reader.choice.filter:
    class: HeimrichHannot\ReaderBundle\Choice\FilterChoice
    arguments:
      - "@contao.framework"

  huh.reader.choice.parent-reader-config:
    class: HeimrichHannot\ReaderBundle\Choice\ParentReaderConfigChoice
    arguments:
      - "@contao.framework"
      - "@huh.reader.reader-config-registry"

  huh.reader.choice.syndication:
    class: HeimrichHannot\ReaderBundle\Choice\SyndicationChoice
    arguments:
      - "@contao.framework"

  huh.reader.choice.syndication-pdf-reader:
    class: HeimrichHannot\ReaderBundle\Choice\SyndicationPdfReaderChoice
    arguments:
      - "@contao.framework"

  HeimrichHannot\ReaderBundle\Manager\ReaderManager:
    autowire: true
  huh.reader.manager.reader: '@HeimrichHannot\ReaderBundle\Manager\ReaderManager'

  HeimrichHannot\ReaderBundle\Registry\ReaderConfigRegistry:
    arguments:
      - "@contao.framework"
      - "@huh.filter.manager"
      - "@huh.utils.model"
      - "@huh.utils.dca"
  huh.reader.reader-config-registry: '@HeimrichHannot\ReaderBundle\Registry\ReaderConfigRegistry'

  HeimrichHannot\ReaderBundle\Registry\ReaderConfigElementRegistry:
    autowire: true
  huh.reader.reader-config-element-registry: '@HeimrichHannot\ReaderBundle\Registry\ReaderConfigElementRegistry'

  huh.reader.util.reader-config-element-util:
    class: HeimrichHannot\ReaderBundle\Util\ReaderConfigElementUtil
    arguments:
      - "@contao.framework"
      - "@huh.reader.reader-config-registry"
      - "@huh.reader.reader-config-element-registry"
      - "@huh.utils.choice.field"

  huh.reader.util.reader-config-util:
    class: HeimrichHannot\ReaderBundle\Util\ReaderConfigUtil
    arguments:
      - "@contao.framework"
      - "@huh.reader.reader-config-registry"
      - "@huh.utils.choice.field"
      - "@huh.utils.model"
      - "@huh.utils.dca"

  huh.reader.backend.module:
    class: HeimrichHannot\ReaderBundle\Backend\Module

  huh.reader.query_builder:
    class: HeimrichHannot\ReaderBundle\QueryBuilder\ReaderQueryBuilder
    shared: false
    arguments:
      - "@contao.framework"
      - "@doctrine.dbal.default_connection"

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  twig.extension.array:
    class: Twig_Extensions_Extension_Array
    tags:
      - { name: twig.extension }

  twig.extension.date:
    class: Twig_Extensions_Extension_Date
    tags:
      - { name: twig.extension }
    arguments:
      - "@translator"

  twig.truncate.service:
    class: Urodoz\Truncate\TruncateService

  twig.extension.truncate.html:
    class: Urodoz\Truncate\Bridge\Twig\TruncateExtension
    arguments:
      - "@twig.truncate.service"
    tags:
      - { name: twig.extension }

  HeimrichHannot\ReaderBundle\ConfigElementType\CommentConfigElementType: ~
  HeimrichHannot\ReaderBundle\ConfigElementType\ImageConfigElementType: ~
