services:
    huh.reader.choice.template.item:
        class: HeimrichHannot\ReaderBundle\Choice\ReaderItemTemplateChoice
        arguments:
            - "@contao.framework"
    huh.reader.choice.parent-reader-config:
        class: HeimrichHannot\ReaderBundle\Choice\ParentReaderConfigChoice
        arguments:
            - "@contao.framework"
    huh.reader.reader-config-registry:
        class: HeimrichHannot\ReaderBundle\Registry\ReaderConfigRegistry
        arguments:
            - "@contao.framework"
    huh.reader.reader-config-element-registry:
        class: HeimrichHannot\ReaderBundle\Registry\ReaderConfigElementRegistry
        arguments:
            - "@contao.framework"