services:
    huh.reader.backend.reader-config:
        class: HeimrichHannot\ReaderBundle\Backend\ReaderConfig
        arguments:
            - "@contao.framework"
            - "@huh.reader.reader-config-registry"
            - "@huh.utils.model"
            - "@huh.utils.dca"
    huh.reader.backend.reader-config-element:
        class: HeimrichHannot\ReaderBundle\Backend\ReaderConfigElement
        arguments:
            - "@contao.framework"
    huh.reader.choice.template.item:
        class: HeimrichHannot\ReaderBundle\Choice\ReaderItemTemplateChoice
        arguments:
            - "@contao.framework"
    huh.reader.choice.manager:
        class: HeimrichHannot\ReaderBundle\Choice\ManagerChoice
        arguments:
            - "@contao.framework"
    huh.reader.choice.item:
        class: HeimrichHannot\ReaderBundle\Choice\ItemChoice
        arguments:
            - "@contao.framework"
    huh.reader.choice.parent-reader-config:
        class: HeimrichHannot\ReaderBundle\Choice\ParentReaderConfigChoice
        arguments:
            - "@contao.framework"
            - "@huh.reader.reader-config-registry"
    huh.reader.manager.reader:
        class: HeimrichHannot\ReaderBundle\Manager\ReaderManager
        arguments:
            - "@contao.framework"
            - "@huh.entity_filter.backend.entity_filter"
            - "@huh.reader.reader-config-registry"
            - "@huh.reader.reader-config-element-registry"
            - "@huh.utils.model"
            - "@huh.utils.url"
            - "@huh.utils.container"
            - "@huh.utils.image"
            - "@huh.utils.form"
            - "@twig"
    huh.reader.reader-config-registry:
        class: HeimrichHannot\ReaderBundle\Registry\ReaderConfigRegistry
        arguments:
            - "@contao.framework"
            - "@huh.filter.registry"
            - "@huh.utils.model"
            - "@huh.utils.dca"
    huh.reader.reader-config-element-registry:
        class: HeimrichHannot\ReaderBundle\Registry\ReaderConfigElementRegistry
        arguments:
            - "@contao.framework"
            - "@huh.reader.reader-config-registry"
            - "@huh.utils.model"
    huh.reader.util.reader-config-element-util:
        class: HeimrichHannot\ReaderBundle\Util\ReaderConfigElementUtil
        arguments:
            - "@contao.framework"
            - "@huh.reader.reader-config-registry"
            - "@huh.reader.reader-config-element-registry"
            - "@huh.utils.choice.field"
    huh.reader.util.reader-config-util:
        class: HeimrichHannot\ReaderBundle\Util\ReaderConfigUtil
        arguments:
            - "@contao.framework"
            - "@huh.reader.reader-config-registry"
            - "@huh.utils.choice.field"
            - "@huh.utils.model"
            - "@huh.utils.dca"
    huh.reader.backend.module:
        class: HeimrichHannot\ReaderBundle\Backend\Module